version: "2"

services:
  neo4j:
    image: neo4j:4.2-enterprise
    networks:
      - host
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_unmanagedExtensionClasses=semantics.extension=/rdf
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["apoc","graph-data-science","n10s"]
      - NEO4J_dbms_memory_heap_initial__size=${NEO4J_dbms_memory_heap_initial__size:-4600m}
      - NEO4J_dbms_memory_heap_max__size=${NEO4J_dbms_memory_heap_max__size:-4600m}
      - NEO4J_dbms_memory_pagecache_size=${NEO4J_dbms_memory_pagecache_size:-1g}
    volumes:
      - ./neo4j/data:/data

  zeppelin:
    image: utnaf/zeppelin:0.8.2
    networks:
      - host
    ports:
      - 8080:8080
    environment: 
      - ZEPPELIN_ADDR=0.0.0.0
    volumes:
      - ./zeppelin/notebook:/zeppelin/notebook
      - ./zeppelin/conf:/zeppelin/conf
      - ./zeppelin/data:/zeppelin/spark-warehouse
      - ./zeppelin/jars:/jars
      - ./zeppelin/interpreter/neo4j:/zeppelin/interpreter/neo4j

networks:
  host:
