version: "2"

services:
  neo4j:
    image: neo4j:4.1.2
    networks:
      - host
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_unmanagedExtensionClasses=semantics.extension=/rdf
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["apoc","graph-data-science","n10s"]
    volumes:
      # - ./neo4j/plugins:/plugins
      - ./neo4j/data:/data

  zeppelin:
    image: apache/zeppelin:0.9.0
    networks:
      - host
    ports:
      - 8080:8080
    volumes:
      - ./zeppelin/notebook:/zeppelin/notebook
      - ./zeppelin/conf:/zeppelin/conf
      - ./zeppelin/data:/zeppelin/spark-warehouse
      - ./zeppelin/jars:/jars
      - ./zeppelin/interpreter/neo4j:/zeppelin/interpreter/neo4j

networks:
  host:
